"""create temperature table

Revision ID: 30199524b775
Revises: 
Create Date: 2022-03-02 12:08:43.101287

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '30199524b775'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temperatures',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('temperature', sa.String(
                        length=5), nullable=False),
                    sa.Column('humidity', sa.String(length=5), nullable=False),
                    sa.Column('created_time', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('temperatures')
    # ### end Alembic commands ###
